#!/usr/bin/env python3
"""RhinoMCP Plugin Installer.

Generates a one-click loader script that users can run in Rhino to start the plugin.

Usage:
    python scripts/install_rhino_plugin.py
    python scripts/install_rhino_plugin.py --plugin-dir /path/to/rhino_plugin --output-dir /custom/output
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


def get_plugin_dir() -> Path:
    return Path(__file__).parent.parent / "src" / "rhino_plugin"


def generate_loader_script(plugin_dir: Path, host: str = "localhost", port: int = 9876) -> str:
    """Generate a Python script that can be run inside Rhino to start the socket server."""
    plugin_path_str = str(plugin_dir).replace("\\", "/")
    return f'''# RhinoMCP Plugin Loader
# Run this script in Rhino via: _RunPythonScript
# Generated by install_rhino_plugin.py

import sys
import os

# Add plugin directory to Python path
plugin_dir = r"{plugin_path_str}"
if plugin_dir not in sys.path:
    sys.path.insert(0, plugin_dir)

try:
    import socket_server
    socket_server.HOST = "{host}"
    socket_server.PORT = {port}
    socket_server.start()
    print("[RhinoMCP] Plugin loaded and server started on {host}:{port}")
    print("[RhinoMCP] The AI can now control Rhino!")
except Exception as e:
    print("[RhinoMCP] ERROR: " + str(e))
    import traceback
    traceback.print_exc()
'''


def generate_rhino_startup_script(plugin_dir: Path, host: str, port: int) -> str:
    """Generate a script for Rhino's startup scripts directory (auto-load on Rhino start)."""
    return generate_loader_script(plugin_dir, host, port)


def main() -> None:
    parser = argparse.ArgumentParser(description="Install RhinoMCP Plugin")
    parser.add_argument("--plugin-dir", type=Path, default=None,
                        help="Path to rhino_plugin directory")
    parser.add_argument("--output-dir", type=Path, default=Path.home() / "RhinoMCP",
                        help="Directory to write loader scripts")
    parser.add_argument("--host", default="localhost")
    parser.add_argument("--port", type=int, default=9876)
    args = parser.parse_args()

    plugin_dir = args.plugin_dir or get_plugin_dir()
    if not plugin_dir.exists():
        print(f"ERROR: Plugin directory not found: {plugin_dir}")
        sys.exit(1)

    output_dir: Path = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    # Write the loader script
    loader_path = output_dir / "rhino_mcp_start.py"
    loader_script = generate_loader_script(plugin_dir, args.host, args.port)
    loader_path.write_text(loader_script, encoding="utf-8")

    print(f"\n=== RhinoMCP Plugin Installer ===")
    print(f"\n✓ Loader script written to: {loader_path}")
    print(f"\n=== How to Start the Plugin in Rhino ===")
    print(f"\nOption 1 — Manual (each session):")
    print(f"  1. Open Rhino 8")
    print(f"  2. Type in command line: _RunPythonScript")
    print(f"  3. Browse to: {loader_path}")
    print(f"  4. Press Enter")
    print(f"\nOption 2 — Auto-load (every Rhino startup):")
    print(f"  Copy the loader script to Rhino's startup scripts folder:")

    # Print OS-specific startup folder paths
    if sys.platform == "win32":
        roaming = os.environ.get("APPDATA", "C:\\Users\\YourName\\AppData\\Roaming")
        startup_dir = f"{roaming}\\McNeel\\Rhinoceros\\8.0\\scripts"
    else:
        startup_dir = "~/Library/Application Support/McNeel/Rhinoceros/8.0/scripts"

    print(f"    {startup_dir}")
    print(f"\nOption 3 — From Rhino Python editor:")
    print(f"  Open the Python editor (Tools > Python Editor), paste:")
    print(f"  import sys; sys.path.insert(0, r'{plugin_dir}')")
    print(f"  import socket_server; socket_server.start()")

    print(f"\n=== MCP Server Configuration ===")
    print(f"\nAdd this to your Claude Desktop config (~/.config/claude/claude_desktop_config.json):")
    config = {
        "mcpServers": {
            "rhino": {
                "command": "python",
                "args": ["-m", "rhino_mcp.server"],
                "env": {
                    "RHINO_HOST": args.host,
                    "RHINO_PORT": str(args.port),
                },
            }
        }
    }
    import json
    print(json.dumps(config, indent=2))
    print()


if __name__ == "__main__":
    main()
